package entity;

// Generated 25-Nov-2013 20:54:41 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserAddressHistoryId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class UserAddressHistoryId implements java.io.Serializable {

	private int userId;
	private int addressId;
	private Date dateFrom;

	public UserAddressHistoryId() {
	}

	public UserAddressHistoryId(int userId, int addressId, Date dateFrom) {
		this.userId = userId;
		this.addressId = addressId;
		this.dateFrom = dateFrom;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "address_id", nullable = false)
	public int getAddressId() {
		return this.addressId;
	}

	public void setAddressId(int addressId) {
		this.addressId = addressId;
	}

	@Column(name = "date_from", nullable = false, length = 19)
	public Date getDateFrom() {
		return this.dateFrom;
	}

	public void setDateFrom(Date dateFrom) {
		this.dateFrom = dateFrom;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserAddressHistoryId))
			return false;
		UserAddressHistoryId castOther = (UserAddressHistoryId) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getAddressId() == castOther.getAddressId())
				&& ((this.getDateFrom() == castOther.getDateFrom()) || (this
						.getDateFrom() != null
						&& castOther.getDateFrom() != null && this
						.getDateFrom().equals(castOther.getDateFrom())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getAddressId();
		result = 37 * result
				+ (getDateFrom() == null ? 0 : this.getDateFrom().hashCode());
		return result;
	}

}
