package model;

// Generated 25-Nov-2013 20:54:41 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

/**
 * Address generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "address")
public class Address implements java.io.Serializable {

	private Integer addressId;
	private String street;
	private int buildingNumber;
	private String city;
	private int zipCode;
	private Set<UserAddressHistory> userAddressHistories = new HashSet<UserAddressHistory>(
			0);

	public Address() {
	}

	public Address(String street, int buildingNumber, String city, int zipCode) {
		this.street = street;
		this.buildingNumber = buildingNumber;
		this.city = city;
		this.zipCode = zipCode;
	}

	public Address(String street, int buildingNumber, String city, int zipCode,
			Set<UserAddressHistory> userAddressHistories) {
		this.street = street;
		this.buildingNumber = buildingNumber;
		this.city = city;
		this.zipCode = zipCode;
		this.userAddressHistories = userAddressHistories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "address_id", unique = true, nullable = false)
	public Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}

	@Column(name = "street", nullable = false)
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "building_number", nullable = false)
	public int getBuildingNumber() {
		return this.buildingNumber;
	}

	public void setBuildingNumber(int buildingNumber) {
		this.buildingNumber = buildingNumber;
	}

	@Column(name = "city", nullable = false)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "zip_code", nullable = false)
	public int getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(int zipCode) {
		this.zipCode = zipCode;
	}

	@OneToMany(mappedBy = "address")
	@LazyCollection(LazyCollectionOption.FALSE)
	public Set<UserAddressHistory> getUserAddressHistories() {
		return this.userAddressHistories;
	}

	public void setUserAddressHistories(
			Set<UserAddressHistory> userAddressHistories) {
		this.userAddressHistories = userAddressHistories;
	}

	@Override
	public String toString() {
		return "Address [addressId=" + addressId + ", street=" + street
				+ ", buildingNumber=" + buildingNumber + ", city=" + city
				+ ", zipCode=" + zipCode + ", userAddressHistories="
				+ userAddressHistories + "]";
	}

	
}
