package model;

// Generated 25-Nov-2013 20:54:41 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

/**
 * PaymentMethod generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "payment_method")
public class PaymentMethod implements java.io.Serializable {

	private Integer paymentMethodId;
	private String description;
	private Set<User> users = new HashSet<User>(0);

	public PaymentMethod() {
	}

	public PaymentMethod(String description) {
		this.description = description;
	}

	public PaymentMethod(String description, Set<User> users) {
		this.description = description;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "payment_method_id", unique = true, nullable = false)
	public Integer getPaymentMethodId() {
		return this.paymentMethodId;
	}

	public void setPaymentMethodId(Integer paymentMethodId) {
		this.paymentMethodId = paymentMethodId;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(mappedBy = "paymentMethod")
	@LazyCollection(LazyCollectionOption.FALSE)
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
